import {
  pgTable,
  text,
  timestamp,
  uuid,
  real,
  integer,
  index,
  uniqueIndex,
  primaryKey,
} from "drizzle-orm/pg-core";

export const decks = pgTable(
  "decks",
  {
    id: uuid("id").primaryKey(),
    userId: text("userId").notNull(),
    name: text("name").notNull(),
    sourceFileName: text("sourceFileName").notNull(),
    createdAt: timestamp("createdAt", { mode: "string" }).defaultNow().notNull(),
  },
  (table) => [index("decks_userId_idx").on(table.userId)]
);

export const cards = pgTable(
  "cards",
  {
    id: uuid("id").primaryKey(),
    deckId: uuid("deckId")
      .notNull()
      .references(() => decks.id, { onDelete: "cascade" }),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
    easinessFactor: real("easinessFactor").default(2.5).notNull(),
    interval: integer("interval").default(0).notNull(),
    repetitions: integer("repetitions").default(0).notNull(),
    nextReviewDate: text("nextReviewDate").notNull(),
    illustration: text("illustration"), // nullable SVG string generated by AI
    createdAt: timestamp("createdAt", { mode: "string" }).defaultNow().notNull(),
  },
  (table) => [
    index("cards_deckId_idx").on(table.deckId),
    index("cards_nextReviewDate_idx").on(table.nextReviewDate),
  ]
);

export const tags = pgTable(
  "tags",
  {
    id: uuid("id").primaryKey(),
    userId: text("userId").notNull(),
    name: text("name").notNull(),
    createdAt: timestamp("createdAt", { mode: "string" }).defaultNow().notNull(),
  },
  (table) => [
    index("tags_userId_idx").on(table.userId),
    uniqueIndex("tags_userId_name_idx").on(table.userId, table.name),
  ]
);

export const deckTags = pgTable(
  "deck_tags",
  {
    deckId: uuid("deckId")
      .notNull()
      .references(() => decks.id, { onDelete: "cascade" }),
    tagId: uuid("tagId")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
  },
  (table) => [
    primaryKey({ columns: [table.deckId, table.tagId] }),
    index("deckTags_deckId_idx").on(table.deckId),
    index("deckTags_tagId_idx").on(table.tagId),
  ]
);
